In [2]:
import pandas as pd
vehicles_df = pd.read_csv('../vehicles_us.csv')
vehicles_df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [3]:
vehicles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [4]:
vehicles_df['date_posted'] = pd.to_datetime(vehicles_df['date_posted'])
vehicles_df['is_4wd'] = vehicles_df['is_4wd'].fillna(0)
vehicles_df['is_4wd'] = vehicles_df['is_4wd'].astype(int)
vehicles_df['is_4wd'].value_counts()
vehicles_df['paint_color'] = vehicles_df['paint_color'].fillna('unknown')
vehicles_df['model_year'] = vehicles_df['model_year'].fillna(vehicles_df['model_year'].median())
vehicles_df['model_year'] = vehicles_df['model_year'].astype(int)
vehicles_df['odometer'] = vehicles_df['odometer'].fillna(vehicles_df['odometer'].median())
vehicles_df['odometer'] = vehicles_df['odometer'].astype(int)
vehicles_df['cylinders'] = vehicles_df['cylinders'].fillna(vehicles_df['cylinders'].mode()[0])
vehicles_df['cylinders'] = vehicles_df['cylinders'].astype(int)
vehicles_df['transmission'] = vehicles_df['transmission'].fillna('unknown')
vehicles_df['price'] = vehicles_df['price'].fillna(vehicles_df['price'].median())
vehicles_df['price'] = vehicles_df['price'].astype(int)

vehicles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    51525 non-null  int64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     51525 non-null  int64
 5   fuel          51525 non-null  str
 6   odometer      51525 non-null  int64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   51525 non-null  str
 10  is_4wd        51525 non-null  int64
 11  date_posted   51525 non-null  datetime64[us]
 12  days_listed   51525 non-null  int64
dtypes: datetime64[us](1), int64(6), str(6)
memory usage: 7.2 MB

In [5]:
import plotly.express as px
myear_fig = px.histogram(vehicles_df, x='model_year', nbins=20, title='Distribution of Model Year')
myear_fig

In [6]:
price_grp = vehicles_df.groupby('model_year')['price'].mean().reset_index()
price_fig = px.scatter(price_grp, x='model_year', y='price', title='Average Price by Model Year')
price_fig

In [7]:
odom_fig = px.scatter(vehicles_df, x='odometer', y='price', title='Odometer vs. Price')
odom_fig

In [8]:
vehicles_df.sample(3)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
35231,6100,2014,dodge charger,fair,6,gas,166686,automatic,sedan,silver,0,2019-03-21,3
5479,2900,2005,jeep liberty,good,6,gas,203000,automatic,SUV,blue,1,2018-10-03,77
18100,1900,2000,ford mustang,fair,6,gas,130000,automatic,convertible,black,0,2018-05-03,41